title: "read books" # name of the site
author: xiangmouren # name of site's author
email: resmile0927@gmail.com # email of site's author
url: https://i1oveyou.github.io # root address of the site
baseurl: "/books" # subpath of the site, e.g. "/blog" (leave it blank "" if you're site shouldn't use a subpath)
description: > # description of the site (multiple lines allowed)
  最廉价的进步 => 阅读书籍!

permalink: /:month/:day/:title

favicon: "assets/icon/logo.png" # name+extension of favicon (which must be put on the root folder)
# goat_counter: "yoursitename" # put your GoatCounter name if you want to use GoatCounter analytics

#theme: no-style-please # if you are using GitHub Pages, change it to remote_theme: riggraz/no-style-please
remote_theme: riggraz/no-style-please


theme_config:
  appearance: "light" # can be "light", "dark" or "auto"
  back_home_text: "<= back to home" # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: true # show blog description in home page

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
